// Maps original (spaces/Persian/parens-laden) upload filenames to safe ascii slugs
// used throughout the ported React app's public/assets folder.
export const ASSET_MAP = {
  '2.png': 'goat-mask-0.png',
  '3.png': 'goat-mask-1.png',
  '4.png': 'goat-mask-2.png',
  'pasted-1789292357415-0.png': 'goat-pattern-eslimi.png',
  'images (13).jpg': 'goat-pattern-boteh.jpg',
  'shah abbasi.jpg': 'shah-abbasi.jpg',
  'eslimi_transparent.png': 'eslimi-transparent.png',
  'Anahita.jpg': 'card-shelem.jpg',
  'Darious.jpg': 'card-hokm.jpg',
  'Kaveh.jpg': 'card-bebe.jpg',
  'Aparat (رسانیکا) (1).png': 'aparat-logo.png',
  'Gemini_Generated_Image_1i45we1i45we1i4wew-bf222c6f.jpg': 'hokm-howto-bg.jpg',
  'Gemini_Generated_Image_1xpjse1xpjse1xpj.jpg': 'bebe-hero-bg.jpg',
  'Gemini_Generated_Image_20zwz420zwz420zw.jpg': 'shelem-hero-bg.jpg',
  'Gemini_Generated_Image_4izft94izft94izf-removebg-preview (1).png': 'shelem-mobile.png',
  'Gemini_Generated_Image_51b3an51b3an51b3.jpg': 'shelem-howto-bg.jpg',
  'Gemini_Generated_Image_6dy23u6dy23u6dy2.jpg': 'shelem-reason-2.jpg',
  'Gemini_Generated_Image_9veshp9veshp9ves.jpg': 'hokm-reason-1.jpg',
  'Gemini_Generated_Image_cbpqnycbpqnycbpq.jpg': 'bebe-reason-1.jpg',
  'Gemini_Generated_Image_dulgkydulgkydulg.jpg': 'shelem-reason-1.jpg',
  'Gemini_Generated_Image_fx52s5fx52s5fx52.jpg': 'bebe-howto-bg.jpg',
  'Gemini_Generated_Image_jw7c89jw7c89jw7c-removebg-preview (1).png': 'hokm-mobile.png',
  'Gemini_Generated_Image_mb7mpimb7mpimb7m.jpg': 'hokm-reason-2.jpg',
  'Gemini_Generated_Image_oquw82oquw82oquw.jpg': 'bebe-reason-2.jpg',
  'Gemini_Generated_Image_r2yswtr2yswtr2ys-removebg-preview.png': 'bebe-mobile.png',
  'Gemini_Generated_Image_sho69esho69esho6.jpg': 'hokm-hero-bg.jpg',
  'Gemini_Generated_Image_up3i8pup3i8pup3i.jpg': 'birad-banner.jpg',
  'heriz_antique_van245896_265x380_oriental_carpet_persian_carpet.jpg': 'home-carpet-bg.jpg',
  'Playing_cards_fan_out_across_t.mp4': 'home-hero-video.mp4',
  'use_hakemam_website_and_creat.mp4': 'preview-video.mp4',
};
